"""context-grid: a lab for grounding pipelines.

Sweep parser x chunker x embedder x index x reranker on your own documents, and get back
ranked, reproducible results scored on quality, latency and cost.

Everything rests on one property: a piece of text always knows which characters of which
source document it came from. That is what makes comparing two chunkers -- or two parsers --
a valid thing to do at all.
"""

from __future__ import annotations

from contextgrid.assemble import AssembledContext, ContextAssembler, Ordering, tokens_sent
from contextgrid.cache import Cache, CacheStats, DiskCache, MemoryCache, NullCache
from contextgrid.chunk import CHUNKERS, ChunkerError, SemanticChunker, get_chunker
from contextgrid.core.errors import (
    ContextGridError,
    DocumentError,
    EvalSetError,
    MissingExtraError,
    ResolutionError,
    SpanError,
)
from contextgrid.core.protocols import Chunker, Parser, Tokenizer
from contextgrid.core.registry import Registry, UnknownPluginError
from contextgrid.core.types import (
    Block,
    BlockKind,
    Chunk,
    ChunkSet,
    Document,
    EvalItem,
    EvalSet,
    GoldAnchor,
    GoldSpan,
    MediaType,
    ParsedDocument,
    QuestionType,
    RelevanceLabel,
    RetrievedChunk,
    SourceFile,
    Span,
    coverage_fraction,
    covered_length,
    intersection_length,
    merge_spans,
    total_length,
)
from contextgrid.core.warnings import GridWarning, Severity, WarningCode, WarningLog
from contextgrid.corpus import (
    Corpus,
    CorpusError,
    CorpusFingerprint,
    fingerprint,
    fingerprint_sources,
)
from contextgrid.cost import PRICES, CostBreakdown, CostModel, Pricing
from contextgrid.diagnose import Diagnosis, FailurePoint, FailureReport, diagnose
from contextgrid.embed import (
    EMBEDDERS,
    AdaptedEmbedder,
    Embedder,
    LinearAdapter,
    Triplet,
    fit_adapter,
    get_embedder,
    mine_triplets,
    split_triplets,
)
from contextgrid.evalset import (
    Classifier,
    EvalSetQuality,
    FilterChain,
    FilterResult,
    KeywordProbeGenerator,
    LLMQuestionGenerator,
    RecordingLLM,
    ReviewQueue,
    Verdict,
    assess,
    default_filters,
    read_beir,
    read_csv,
    read_jsonl,
    read_legalbench_rag,
    write_csv,
    write_jsonl,
)
from contextgrid.generate import (
    Answer,
    AnswerScore,
    ExtractiveGenerator,
    GenerationReport,
    Generator,
    LLMGenerator,
    lift,
    score_answer,
)
from contextgrid.grid import Matrix, Runner, SweepMode, estimate_cost, matrix
from contextgrid.index import (
    INDEXES,
    Index,
    Quantization,
    QuantizedDenseIndex,
    get_index,
    recall_against_exact,
)
from contextgrid.lab import Lab
from contextgrid.parse import PARSERS, get_parser
from contextgrid.pipeline import BuiltPipeline, Config, Timings, build
from contextgrid.report import (
    Manifest,
    Results,
    RunResult,
    build_manifest,
    config_to_python,
    config_to_yaml,
    explain_diff,
    format_leaderboard,
    results_to_json,
    results_to_markdown,
    winning_config_to_yaml,
    write_bundle,
)
from contextgrid.rerank import RERANKERS, Reranker, get_reranker
from contextgrid.score import METRICS, Metric, get_metric
from contextgrid.score.anchor import (
    AnchorMatch,
    AnchorResolver,
    MatchStrategy,
    collapse_whitespace,
)
from contextgrid.score.metrics import DEFAULT_KS, available_metrics, evaluate, per_query
from contextgrid.score.resolve import (
    GoldResolution,
    Resolution,
    ResolutionPolicy,
    SpanResolver,
    character_f1,
    character_precision,
    character_recall,
    gold_coverage_by_chunk,
    retrieved_character_count,
)
from contextgrid.score.significance import (
    Comparison,
    Interval,
    bootstrap_interval,
    paired_bootstrap,
    randomisation_test,
)
from contextgrid.tokens import TOKENIZERS, get_tokenizer
from contextgrid.transform import (
    TRANSFORMS,
    Decompose,
    ExpandAcronyms,
    HyDE,
    MultiQuery,
    NoTransform,
    QueryTransform,
    StepBack,
    TransformedQuery,
    get_transform,
)
from contextgrid.validate import ValidationResult, load_benchmark, self_check, validate

__version__ = "0.9.0"

__all__ = [
    "CHUNKERS",
    "DEFAULT_KS",
    "EMBEDDERS",
    "INDEXES",
    "METRICS",
    "PARSERS",
    "PRICES",
    "RERANKERS",
    "TOKENIZERS",
    "TRANSFORMS",
    "AdaptedEmbedder",
    "AnchorMatch",
    "AnchorResolver",
    "Answer",
    "AnswerScore",
    "AssembledContext",
    "Block",
    "BlockKind",
    "BuiltPipeline",
    "Cache",
    "CacheStats",
    "Chunk",
    "ChunkSet",
    "Chunker",
    "ChunkerError",
    "Classifier",
    "Comparison",
    "Config",
    "ContextAssembler",
    "ContextGridError",
    "Corpus",
    "CorpusError",
    "CorpusFingerprint",
    "CostBreakdown",
    "CostModel",
    "Decompose",
    "Diagnosis",
    "DiskCache",
    "Document",
    "DocumentError",
    "Embedder",
    "EvalItem",
    "EvalSet",
    "EvalSetError",
    "EvalSetQuality",
    "ExpandAcronyms",
    "ExtractiveGenerator",
    "FailurePoint",
    "FailureReport",
    "FilterChain",
    "FilterResult",
    "GenerationReport",
    "Generator",
    "GoldAnchor",
    "GoldResolution",
    "GoldSpan",
    "GridWarning",
    "HyDE",
    "Index",
    "Interval",
    "KeywordProbeGenerator",
    "LLMGenerator",
    "LLMQuestionGenerator",
    "Lab",
    "LinearAdapter",
    "Manifest",
    "MatchStrategy",
    "Matrix",
    "MediaType",
    "MemoryCache",
    "Metric",
    "MissingExtraError",
    "MultiQuery",
    "NoTransform",
    "NullCache",
    "Ordering",
    "ParsedDocument",
    "Parser",
    "Pricing",
    "Quantization",
    "QuantizedDenseIndex",
    "QueryTransform",
    "QuestionType",
    "RecordingLLM",
    "Registry",
    "RelevanceLabel",
    "Reranker",
    "Resolution",
    "ResolutionError",
    "ResolutionPolicy",
    "Results",
    "RetrievedChunk",
    "ReviewQueue",
    "RunResult",
    "Runner",
    "SemanticChunker",
    "Severity",
    "SourceFile",
    "Span",
    "SpanError",
    "SpanResolver",
    "StepBack",
    "SweepMode",
    "Timings",
    "Tokenizer",
    "TransformedQuery",
    "Triplet",
    "UnknownPluginError",
    "ValidationResult",
    "Verdict",
    "WarningCode",
    "WarningLog",
    "__version__",
    "assess",
    "available_metrics",
    "bootstrap_interval",
    # `cg.build` is the call every exported snippet ends on, and the one the docs have always
    # written. It only ever resolved because `contextgrid.pipeline` happened to be left as an
    # attribute by an internal import -- a private name doing public work. Exported properly.
    "build",
    "build_manifest",
    "character_f1",
    "character_precision",
    "character_recall",
    "collapse_whitespace",
    "config_to_python",
    "config_to_yaml",
    "coverage_fraction",
    "covered_length",
    "default_filters",
    "diagnose",
    "estimate_cost",
    "evaluate",
    "explain_diff",
    "fingerprint",
    "fingerprint_sources",
    "fit_adapter",
    "format_leaderboard",
    "get_chunker",
    "get_embedder",
    "get_index",
    "get_metric",
    "get_parser",
    "get_reranker",
    "get_tokenizer",
    "get_transform",
    "gold_coverage_by_chunk",
    "intersection_length",
    "lift",
    "load_benchmark",
    "matrix",
    "merge_spans",
    "mine_triplets",
    "paired_bootstrap",
    "per_query",
    "randomisation_test",
    "read_beir",
    "read_csv",
    "read_jsonl",
    "read_legalbench_rag",
    "recall_against_exact",
    "results_to_json",
    "results_to_markdown",
    "retrieved_character_count",
    "score_answer",
    "self_check",
    "split_triplets",
    "tokens_sent",
    "total_length",
    "validate",
    "winning_config_to_yaml",
    "write_bundle",
    "write_csv",
    "write_jsonl",
]
